# Generated by Django 4.2.9 on 2024-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_image_event_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="images",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
