# Generated by Django 4.2.9 on 2024-05-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_meeting_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service", old_name="description", new_name="end_time",
        ),
        migrations.RenameField(
            model_name="service", old_name="time", new_name="start_time",
        ),
        migrations.RemoveField(model_name="service", name="location",),
    ]
