# Generated by Django 4.2.9 on 2024-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_description_service_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service", name="end_time", field=models.TimeField(),
        ),
    ]
