# Generated by Django 4.2.9 on 2024-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_service_end_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="images",),
        migrations.AddField(
            model_name="event",
            name="images",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
