# Generated by Django 4.2.9 on 2024-05-21 21:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="availability",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="interests",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("teaching", "Teaching"),
                    ("cooking", "Cooking"),
                    ("driving", "Driving"),
                    ("cleaning", "Cleaning"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="skills",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("teaching", "Teaching"),
                    ("cooking", "Cooking"),
                    ("driving", "Driving"),
                    ("cleaning", "Cleaning"),
                ],
                max_length=100,
            ),
        ),
    ]
