# Generated by Django 4.2.9 on 2024-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_alter_volunteer_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="address",
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
