# Generated by Django 4.2.9 on 2024-06-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_member_user"),
        ("volunteers", "0003_alter_volunteer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="Volunteer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
            ),
        ),
    ]
