# Generated by Django 4.2.9 on 2024-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0005_alter_volunteer_volunteer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
