# Generated by Django 4.2.9 on 2024-06-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_admin"),
        ("volunteers", "0006_alter_volunteer_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="volunteer", name="Volunteer",),
        migrations.AddField(
            model_name="volunteer",
            name="volunteer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
            ),
        ),
    ]
