# Generated by Django 4.2.9 on 2024-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
