# Generated by Django 4.2.9 on 2024-06-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_admin"),
        ("dashboard", "0003_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="sender",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
            ),
        ),
    ]
