# Generated by Django 4.2.9 on 2024-07-03 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_admin"),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="FinancialTransaction",),
        migrations.RemoveField(model_name="donation", name="donation_date",),
        migrations.RemoveField(model_name="donation", name="donor_name",),
        migrations.AddField(
            model_name="donation",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donation",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="member",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
            ),
        ),
    ]
