# Generated by Django 4.2.9 on 2024-07-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_delete_financialtransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
