# Generated by Django 4.2.9 on 2024-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(
                max_length=20, null=models.EmailField(max_length=254, unique=True)
            ),
            preserve_default=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
