# Generated by Django 4.2.9 on 2024-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_password_alter_member_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(
                default=models.EmailField(max_length=254, unique=True), max_length=20
            ),
        ),
    ]
