# Generated by Django 4.2.9 on 2024-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
